import { Space } from "contentful-management";

const baseSpace: Space = {
  name: "space-name",
  sys: {
    id: "space-id",
    type: "Space",
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    organization: { sys: { id: "organization-id" } },
  },
  getEnvironment: jest.fn(),
  createApiKey: jest.fn(),
  getApiKeys: jest.fn(),
  createEnvironmentWithId: jest.fn(),
  createApiKeyWithId: jest.fn(),
  createEnvironment: jest.fn(),
  getEnvironments: jest.fn(),
  createEnvironmentAliasWithId: jest.fn(),
  createRoleWithId: jest.fn(),
  createRole: jest.fn(),
  createScheduledAction: jest.fn(),
  createWebhook: jest.fn(),
  createWebhookWithId: jest.fn(),
  createSpaceMembership: jest.fn(),
  createSpaceMembershipWithId: jest.fn(),
  createTeamSpaceMembership: jest.fn(),
  delete: jest.fn(),
  deleteScheduledAction: jest.fn(),
  getApiKey: jest.fn(),
  getEnvironmentAlias: jest.fn(),
  getEnvironmentAliases: jest.fn(),
  getPreviewApiKey: jest.fn(),
  getPreviewApiKeys: jest.fn(),
  getRole: jest.fn(),
  getRoles: jest.fn(),
  getScheduledAction: jest.fn(),
  getScheduledActions: jest.fn(),
  getSpaceMembership: jest.fn(),
  getSpaceMember: jest.fn(),
  getSpaceMembers: jest.fn(),
  getSpaceMemberships: jest.fn(),
  getSpaceUser: jest.fn(),
  getSpaceUsers: jest.fn(),
  getTeamSpaceMembership: jest.fn(),
  getTeamSpaceMemberships: jest.fn(),
  getWebhook: jest.fn(),
  getWebhooks: jest.fn(),
  update: jest.fn(),
  updateScheduledAction: jest.fn(),
  getTeams: jest.fn(),
  toPlainObject: jest.fn(),
};

export const aSpace = (overrideProps: Partial<Space> = {}): Space => ({
  ...baseSpace,
  ...overrideProps,
});
